### ISSUE TITLE
KeyError - What does it mean?

### ISSUE THREAD

**Issue by rpspringuel** [nschloe/betterbib#74]
Here's the traceback:

```
$ betterbib Padraic.bib test.bib

  2%|▉                                         | 21/933 [00:05<04:13,  3.60it/s]
Traceback (most recent call last):
  File "/opt/local/bin/betterbib", line 214, in <module>
    _main()
  File "/opt/local/bin/betterbib", line 41, in _main
    _update_from_source(od, source, args.num_concurrent_requests)
  File "/opt/local/bin/betterbib", line 96, in _update_from_source
    data = future.result()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/betterbib/crossref.py", line 165, in find_unique
    for tp in _bibtex_to_crossref_type(entry.type)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/betterbib/crossref.py", line 36, in _bibtex_to_crossref_type
    return _bibtex_to_crossref_map[bibtex_type]
KeyError: 'webpage'
```

**Comment by nschloe** [comment]
Probably fixed now (cannot confirm for lack of the offending BibTeX entry).

**Comment by rpspringuel** [comment]
Finally got a chance to test this.  I'm still getting a KeyError, but it's now in a different place.  Traceback follows:

```
$ betterbib Padraic.bib test.bib


 26%|██████████▌                              | 242/934 [00:40<01:54,  6.05it/s]Traceback (most recent call last):
  File "/opt/local/bin/betterbib", line 214, in <module>
    _main()
  File "/opt/local/bin/betterbib", line 41, in _main
    _update_from_source(od, source, args.num_concurrent_requests)
  File "/opt/local/bin/betterbib", line 96, in _update_from_source
    data = future.result()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/betterbib/crossref.py", line 180, in find_unique
    return self._crossref_to_pybtex(heuristic_unique_result(results, d))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/betterbib/crossref.py", line 233, in _crossref_to_pybtex
    bibtex_type = self._crossref_to_bibtex_type(data)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/betterbib/crossref.py", line 82, in _crossref_to_bibtex_type
    return _crossref_to_bibtex_type[crossref_type]
KeyError: 'dataset'
```

I'd like to be more useful in providing an excerpt from my bib file which triggers the problem (the whole file is some 934 entries), but the error message doesn't provide me with any clues as to which entry (or set of entries) is causing it.  Perhaps some sort of `--verbose` option which would indicate which entries are being processed by listing their cite-key as they are looked up?

**Comment by nschloe** [comment]
You could add a `print` statement to the code. If not, bisection won't take more than 10 steps anyways (2^10 > 934).

**Comment by nschloe** [comment]
Actually never mind, I think I know what the error is.

**Comment by nschloe** [comment]
Alright, done. Please update and try again.
